### ISSUE TITLE
Haskell homework file organisation

### ISSUE THREAD

**Issue by alexander-lazarov** [googleson78/fp-pract1819#7]
I might be wrong about this, but I think the naming scheme for the Haskell homeworks should be changed a bit.

As far as I understand, in Haskell you can only export functions if you export a module which contains them, and as per convention that module should have the same name as the filename it lives in. However, module names always start with a capital letter but the homework naming convention for the file (`12345.hs`) starts with a number. I suggest to change the naming scheme to be `Fn12345.hs` for the filename and `Fn12345` for the module name.

**Comment by googleson78** [comment]
Uh-oh

Thanks for the heads-up.

I'll fix it, send out a mail, and extend the deadline a bit to compensate for this.
